model_params:
  in_channels: 3
  convbn_blocks: 4 # suggestions: [2,3,4,5]
  conv_kernel_size: [3,3,3,2]
  conv_kernel_strides: [2, 2, 1, 1]
  convbn_channels: [3, 6, 12, 24, 72] 
  conv_activation_fn: 'relu'
  transpose_bn_blocks: 4
  transposebn_channels: [72, 24, 12, 6, 3]
  transpose_kernel_size: [3,3,3,2]
  transpose_kernel_strides: [2, 2, 1, 1]
  transpose_activation_fn: 'relu'
  latent_dim: 72 # suggestions: [12,24,30,36,48,54,60,64,72]
  codebook_size : 10 # suggestions: [10,20,30,40,50,60,70,80,90,100]

train_params:
  batch_size: 72
  epochs: 5
  lr: 0.005
  crit: 'l2'
  reconstruction_loss_weight : 1
  codebook_loss_weight : 1
  commitment_loss_weight : 0.2
  model_name: 'vqvae_nnL4_cdbk10_ld72.pth'
  indices_tensor: 'vqvae_nnL4_cdbk10_ld72.pt'
  seed: 42
  save_training_image: True
  path: /home/mohsen/Desktop/Academia/RUB Research Projects/INI/data/3dshapes/3dshapes.h5  # '/content/drive/MyDrive/Data/3dshapes.h5' 
  output_dir: 'vqvae_outputs'